# Generated by Django 4.1.3 on 2023-09-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_member_name', models.CharField(max_length=200)),
                ('book_name', models.CharField(max_length=50)),
                ('charge', models.IntegerField(help_text='enter price')),
                ('transiction', models.IntegerField(help_text='enter the book want to Issue')),
            ],
        ),
    ]
